import './globals.css'
import NavBar from './nav/NavBar'

export const metadata = {
  title: 'Auction',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <NavBar/>
        <main className='container mx-auto px-5'>
          {children}
        </main>
      </body>
    </html>
  )
}
